module4-task2
htmlacademy-php/2039497-readme-12 pull request #10
Opened 2022-05-14 13:59 UTC by EvgenyRomanov

2022-05-16 07:48 UTC, esbobkov requested changes

2022-05-16 07:48 UTC, esbobkov commented on queries.sql
> +INSERT INTO `type_content` (`type`, `class_name`) VALUES ('Видео', 'post-video');
Можно сократить
```sql
INSERT INTO `type_content` (`type`, `class_name`) VALUES 
('Цитата', 'post-quote'),
 ('Текст', 'post-text');
-- и т.д.
```

2022-05-16 07:48 UTC, esbobkov commented on queries.sql
> +  *
лучше явно указать необходимые поля.

2022-05-16 19:28 UTC, EvgenyRomanov commented on queries.sql
> +INSERT INTO `type_content` (`type`, `class_name`) VALUES ('Видео', 'post-video');
О, классно, так значительно лучше. 
Скорректировал.

2022-05-16 19:29 UTC, EvgenyRomanov commented on queries.sql
> +  *
Тут тоже немного скорректировал.

2022-05-17 09:05 UTC, esbobkov approved these changes

2022-05-17 09:05 UTC, merged