Module6 task1
htmlacademy-php/2039497-readme-12 pull request #12
Opened 2022-06-13 18:52 UTC by EvgenyRomanov

2022-06-14 05:31 UTC, b1rdex requested changes

2022-06-14 05:31 UTC, b1rdex commented on helpers.php
> +function get_diff_date(DateTime $date, string $format = "%d %s назад") : string
В файле helpers.php нужно откатить все изменения, его лучше не редактировать – на защите он не учитывается.

Все свои функции нужно помещать в functions.php (или другие файлы).

2022-06-14 05:31 UTC, b1rdex commented on functions.php
> +                `p`.`content_text` AS `content`,
Тут должен быть такой же case как в get_popular_posts()

2022-06-14 05:31 UTC, b1rdex commented on data/data.php
>  $posts_array = get_popular_posts($link);
Оптимально было бы в функцию get_popular_posts() добавить опциональный аргумент, который бы указывал id категории. Т.к. в текущей ситуации get_popular_posts() вызывается каждый раз, даже если после этого вызывается get_popular_selected_posts()

К тому же, это бы уменьшило копипасту и проблемы, связанные с ней (ниже в get_popular_selected_posts указал что select отличается от get_popular_posts).

2022-06-14 05:31 UTC, b1rdex commented on data/data.php
> +}
1. Можно это упростить: если `isset($_GET['type_post'])`, то достаточно `get_popular_selected_posts($link, (int)$_GET['type_post'])`
2. 404 тут можно убрать, иначе добавлений категорий в бд потребует изменения кода страницы. Как вариант, можно проверить что `$_GET['type_post']` имеется в массиве в `$content_type_array`, если хочется оставить 404 и строго проверять.

2022-06-14 05:31 UTC, b1rdex commented on functions.php
> +        if ($_GET[$type_post] === (string)$id) {
Сравниваются числа, зачем приводить в строку $id? `(int)$_GET[$type_post] === $id`

2022-06-14 05:31 UTC, b1rdex commented on functions.php
> +                `u`.`login` = '$name_user';";
SQL Injection

2022-06-14 05:31 UTC, b1rdex commented on functions.php
> +                *
В таком случае лучше сделать запрос `select count(*) ...`, который вернёт количество строк

2022-06-14 05:31 UTC, b1rdex commented on functions.php
> +                *
`select count(*)...`

2022-06-14 05:31 UTC, b1rdex commented on functions.php
> +                `u`.`login` = '$name_user';";
SQL Injection

2022-06-14 05:31 UTC, b1rdex commented on functions.php
> +                `u`.`login` = '$name_user';";
SQL Injection

2022-06-14 05:31 UTC, b1rdex commented on templates/main.php
> +                        <a class="filters__button filters__button--<?=$type_content['class_name'];?> button <?=getClass('type_post', $id+1);?>" href="?type_post=<?=$id+1;?>">
На $id нельзя полагаться, т.к. это просто порядковый номер в массиве – нет никаких гарантий что он совпадёт с БД. Нужно чтобы в $content_type_array помимо названия был и ID

Либо другой вариант – в ссылке для параметра type_post использовать $type_content['class_name']. Так будут и ссылки человекопонятными, и не придётся оперировать числовым ID.

2022-06-14 05:31 UTC, b1rdex commented on post.php
> +date_default_timezone_set("Europe/Moscow");
Это лучше вынести в config.php, чтобы не копировать каждый раз

2022-06-14 05:31 UTC, b1rdex commented on data/data.php
>  $posts_array = get_popular_posts($link);
И ещё момент – не уверен что этот файл data.php верный, т.к. например на странице просмотра поста зачем доставать из бд популярные посты для главной? Лучше переместить получение данных туда где они используются

2022-06-14 05:31 UTC, b1rdex commented on templates/main_details.php
> +    <h1 class="page__title page__title--publication"><?=$post['header'];?></h1>
Тут и ниже XSS уязвимость – нужно использовать htmlspecialchars

2022-06-14 19:28 UTC, EvgenyRomanov commented on helpers.php
> +function get_diff_date(DateTime $date, string $format = "%d %s назад") : string
ого, не знал

перенес из helpers в functions две функции, которые я написал, get_diff_date в их числе,
поэтому я смело редактировал ее

2022-06-14 21:35 UTC, EvgenyRomanov commented on data/data.php
>  $posts_array = get_popular_posts($link);
согласен, тут я намудрил,
оставил только одну функцию get_popular_posts с аргументом


data.php заменил на другой, где пока еще храним общие данные для index и post
в следующих уроках он не нужен будет совсем, как я понимаю, когда будет реализована аутентификация

2022-06-14 21:37 UTC, EvgenyRomanov commented on data/data.php
> +}
переработал по примеру 1 варианта

2022-06-14 21:38 UTC, EvgenyRomanov commented on functions.php
> +        if ($_GET[$type_post] === (string)$id) {
согласен, глупость..
изменил эту функцию

2022-06-14 21:38 UTC, EvgenyRomanov commented on functions.php
> +                `u`.`login` = '$name_user';";
скорректировал через mysqli_real_escape_string

2022-06-14 21:39 UTC, EvgenyRomanov commented on functions.php
> +                *
исправил

2022-06-14 21:39 UTC, EvgenyRomanov commented on functions.php
> +                *
исправил

2022-06-14 21:39 UTC, EvgenyRomanov commented on functions.php
> +                `u`.`login` = '$name_user';";
скорректировал через mysqli_real_escape_string

2022-06-14 21:39 UTC, EvgenyRomanov commented on functions.php
> +                `u`.`login` = '$name_user';";
скорректировал через mysqli_real_escape_string

2022-06-14 21:40 UTC, EvgenyRomanov commented on templates/main.php
> +                        <a class="filters__button filters__button--<?=$type_content['class_name'];?> button <?=getClass('type_post', $id+1);?>" href="?type_post=<?=$id+1;?>">
скорректировал через $type_content['class_name']

2022-06-14 21:40 UTC, EvgenyRomanov commented on post.php
> +date_default_timezone_set("Europe/Moscow");
скорректировал

2022-06-14 21:40 UTC, EvgenyRomanov commented on templates/main_details.php
> +    <h1 class="page__title page__title--publication"><?=$post['header'];?></h1>
да, такие моменты пропускаю..
скорректировал

2022-06-15 09:35 UTC, b1rdex approved these changes

2022-06-15 09:35 UTC, b1rdex commented on templates/main_details.php
> +            <a class="post-link__external" href="http://<?=$post['content'];?>" title="Перейти по ссылке">
xss

2022-06-15 09:35 UTC, b1rdex commented on templates/main_details.php
> +                <img src="https://www.google.com/s2/favicons?domain=<?=$post['content'];?>" alt="Иконка">
xss

2022-06-15 09:35 UTC, b1rdex commented on templates/main_details.php
> +                <h3><?=$post['title'];?></h3>
xss

2022-06-15 09:35 UTC, b1rdex commented on templates/main_details.php
> +                <span><?=$post['name_user'];?></span>
xss

2022-06-15 09:35 UTC, b1rdex commented on post.php
> +}
В такой ситуации лучше перевенуть if/else, чтобы упростить код:

```php
if (!isset($_GET['id']) || !isset_post($link, $_GET['id'])) {
    header("HTTP/1.1 404 Not Found");
    print("Такой страницы не существует");
    exit();
}

// а тут уже код для отображения поста
```

Обрати внимание, что else не нужен в такой ситуации, т.к. в then происходит exit(). Аналогично можно делать если там return:


```php
function foo($test) {
	if (!$test) {
		return 'error';
	}

	// а тут уже работаем с $test
}
```

2022-06-15 09:35 UTC, merged

2022-06-15 20:00 UTC, EvgenyRomanov commented on post.php
> +}
понял! спасибо!