Module6 task2
htmlacademy-php/2039497-readme-12 pull request #13
Opened 2022-06-26 13:30 UTC by EvgenyRomanov

2022-06-26 13:33 UTC, EvgenyRomanov commented
Загрузить файл картинки локально не получилось. В зону переносится, но не отправляется запросом, а при нажатии конопки не предлагает выбрать файл на компьютере.

2022-06-28 15:53 UTC, EvgenyRomanov commented
Что-то с JS скриптами, попробую разобраться. Если в лейауте их закоментить все, то получается загрузить картинку в блог через выбор файла, иначе она просто добавляется в зону или выбирается из проводника, но не отправляется через запрос.

2022-06-29 12:45 UTC, b1rdex requested changes

2022-06-29 12:45 UTC, b1rdex commented on add.php
> +                if (!in_array($file_type, ["image/gif", "image/png", "image/jpeg"])) {
ещё желательно проверить расширение файла, т.к. можно загрузить `file.php` при этом с mime image/*

2022-06-29 12:45 UTC, b1rdex commented on add.php
> +            move_uploaded_file($_FILES[$field]['tmp_name'], $file_path . $file_name);
тут тоже нужна проверка расширения и mime type

2022-06-29 12:45 UTC, b1rdex commented on add.php
> +        $res = mysqli_stmt_execute($stmt);
лучше вынести целиком в функцию и в ней же обработать ошибку
чтобы функция возвращала $post_id

2022-06-29 12:45 UTC, b1rdex commented on add.php
> +            if (isset_hashtag($link, $post["$type_content-tags"])) {
Логику по тегам тоже стоит сделать сразу внутри функции, которая создаёт пост

2022-06-29 12:45 UTC, b1rdex commented on add.php
> +            header("Location: post.php?id=" . $post_id);
Добавь после этого exit(), чтобы не выполнять остальной код, а сразу делать редирект

2022-06-29 12:45 UTC, b1rdex commented on functions.php
> +        if (!$val) {
Для чего это условие? я так понимаю оно сработает при теге `0`

2022-06-29 12:45 UTC, b1rdex commented on functions.php
> + * @return string
string|null

2022-06-29 12:45 UTC, b1rdex commented on functions.php
> + * @return string
string|null

2022-06-29 12:45 UTC, b1rdex commented on functions.php
> + * @return string
string|null

2022-06-29 12:45 UTC, b1rdex commented on functions.php
> + * @return string
string|null

2022-06-29 12:45 UTC, b1rdex commented on functions.php
> +                `tc`.`class_name` = '$type_content';";
sql injection

2022-06-29 12:45 UTC, b1rdex commented on functions.php
> +function get_fild_for_quote($type_content) {
Не вижу использований функции + опечатка field

2022-06-29 12:45 UTC, b1rdex commented on functions.php
> +function get_content_field($type_content) : string {
не вижу использований функции

2022-06-29 12:45 UTC, b1rdex commented on templates/form_tags.php
> +    <input class="adding-post__input form__input" id="<?=$type_content;?>-tags" type="text" name="<?=$type_content;?>-tags" placeholder="Введите теги" value="<?=get_post_val("$type_content-tags");?>"
xss в value

2022-06-29 12:45 UTC, b1rdex commented on templates/main_add.php
> +                                        <input class="adding-post__input form__input" id="photo-url" type="text" name="photo" placeholder="Введите ссылку" value="<?=get_post_val('photo');?>">
xss в value

2022-06-29 12:45 UTC, b1rdex commented on templates/main_add.php
> +                                        <input class="adding-post__input form__input" id="video-url" type="text" name="video" placeholder="Введите ссылку" value="<?=get_post_val('video');?>">
xss в value

2022-06-29 12:45 UTC, b1rdex commented on templates/main_add.php
> +                                        <textarea class="adding-post__textarea adding-post__textarea--quote form__textarea form__input" id="cite-text" name="quote" placeholder="Текст цитаты"><?=get_p
xss в value

2022-06-29 12:45 UTC, b1rdex commented on templates/main_add.php
> +                                        <input class="adding-post__input form__input" id="quote-author" type="text" name="quote-author" value="<?=get_post_val('quote-author');?>">
xss в value

2022-06-29 12:45 UTC, b1rdex commented on templates/main_add.php
> +                                        <input class="adding-post__input form__input" id="post-link" type="text" name="link" value="<?=get_post_val('link');?>">
xss в value

2022-06-29 12:45 UTC, b1rdex commented on templates/main_add.php
> +                                        <textarea class="adding-post__textarea form__textarea form__input" id="post-text" name="text" placeholder="Введите текст публикации"><?=get_post_val('text');?>
xss в value

2022-07-10 08:53 UTC, EvgenyRomanov commented on functions.php
> +        if (!$val) {
нечасто сталкивался с такой сущностью как тег) 
скорректировал

2022-07-22 04:35 UTC, b1rdex reviewed
Замечания про уникальность имени файла не критичные – насколько я помню, в ТЗ об этом ничего не сказано. Так что на твоё усмотрение, просто имей в виду, что может быть такая проблема.

А замечание про `$file_from = sys_get_temp_dir() . $post['userpic-file-photo'];` нужно проверить и исправить (в рамках следующего задания).

2022-07-22 04:35 UTC, b1rdex commented on add.php
> +            $file_from = sys_get_temp_dir() . $post['userpic-file-photo'];
Думаю `sys_get_temp_dir` тут лишнее, т.к. в `$post['userpic-file-photo']` уже полный путь к картинке из `$_FILES[$field]['name']`

2022-07-22 04:35 UTC, b1rdex commented on add.php
> +            move_uploaded_file($file_from, $file_to);         // rename ??
Да, по-хорошему нужно файлам генерировать новое имя, т.к. иначе есть возможность перезаписать чужой файл :) как вариант, можно использовать например `uniqid()` для генерации имени файла

2022-07-22 04:35 UTC, b1rdex commented on add.php
> +            $file_from = sys_get_temp_dir() . $post['photo'];
А вот тут всё верно 👍  но думаю ещё лучше было бы сразу в `$post['photo']` записать полный путь к файлу (с `sys_get_temp_dir`)

2022-07-22 04:35 UTC, b1rdex commented on add.php
> +            rename($file_from, $file_to);
Тут тоже возможно перезаписать чужой файл, лучше генерировать имя

2022-07-22 04:35 UTC, merged