Module2 task1
htmlacademy-php/2039497-readme-12 pull request #4
Opened 2022-02-18 13:40 UTC by EvgenyRomanov

2022-02-23 08:22 UTC, esbobkov requested changes
Хорошая работа. Нужно внести незначительные правки

2022-02-23 08:22 UTC, esbobkov commented on index.php
> +
не нужное добавление пустой строки

2022-02-23 08:22 UTC, esbobkov commented on index.php
> +			<?php if (1 === $is_auth): ?>
Тут стоит определиться, все-таки Yoda Style везде в сравнении будет использоваться или нет? 
Чтобы сравнения везде выглядяли одиноково и удобнее было читать код.

2022-02-23 08:22 UTC, esbobkov commented on index.php
> +                                    <?=embed_youtube_cover(/* вставьте ссылку на видео */$post['contetnt']); ?>
Опечатка `contetnt`

2022-02-23 08:22 UTC, esbobkov commented on index.php
> +                                    <img src="img/coast-medium.jpg" alt="Превью к видео" width="360" height="188">
функция `embed_youtube_cover` выше итак вставляет img, этот тег лишний

2022-02-26 20:47 UTC, EvgenyRomanov commented
Евгений, спасибо за замечания! Учту в работе.

2022-02-26 20:47 UTC, closed without merging