module2-task2
htmlacademy-php/2039497-readme-12 pull request #6
Opened 2022-03-08 20:25 UTC by EvgenyRomanov

2022-03-11 08:59 UTC, esbobkov requested changes
Функция работает, молодец!

У меня только вопрос насчет крайних случаев, как думаешь, как она должна повести себя, если передать что-то такое?
`cut_text_post('text', 3)`

2022-03-11 08:59 UTC, esbobkov commented on index.php
> +                                    <?= cut_text_post($post['content']); ?>
Из задания я понял, что функцию нужно применить только к `post-text`

> для цитат и ссылок есть ограничение длины при создании поста

2022-03-11 08:59 UTC, esbobkov commented on helpers.php
> +    for ($i = 0; $i < count($text_array); $i++) {
Здесь не критично, но тут `count()` будет вызываться в каждой итерации цикла, что может сказаться на производительности при переборе больших массивов

https://github.com/kalessil/phpinspectionsea/blob/master/docs/performance.md#slow-array-function-used-in-loop

2022-03-12 20:49 UTC, EvgenyRomanov commented on helpers.php
> +    for ($i = 0; $i < count($text_array); $i++) {
Ознакомился с материалом. Добавил и проинициализировал переменную $count рядом с $i.

2022-03-12 20:50 UTC, EvgenyRomanov commented on index.php
> +                                    <?= cut_text_post($post['content']); ?>
Оставил только для post-text.

2022-03-12 20:55 UTC, EvgenyRomanov commented
> 
В контексте примера будет "Не...", т.к. предложение начинается с частицы "не". Длина слова в данном случае укладывается с заданный лимит символов. Если длина слова больше лимита, то будет только многоточие.

2022-03-15 10:59 UTC, esbobkov approved these changes

2022-03-15 10:59 UTC, merged