module3-task1
htmlacademy-php/2039497-readme-12 pull request #7
Opened 2022-03-22 20:50 UTC by EvgenyRomanov

2022-03-25 10:24 UTC, esbobkov requested changes

2022-03-25 10:24 UTC, esbobkov commented on index.php
> +require_once 'data.php';
`data.php` - у тебя лежит в папке templates, здесь будет Warning

2022-03-25 10:24 UTC, esbobkov commented on templates/data.php
> +<?php
т.к. этот файл, точно не относится к шаблонам, лучше положить его в другую папку

2022-03-25 10:24 UTC, esbobkov commented on templates/main.php
> +                        <?php elseif($post['type'] === 'post-text'):?>
текстовая карточка, кажется сломалась. Отображается html код

2022-03-25 10:24 UTC, esbobkov commented on index.php
> +$main = include_template("main.php", ["posts_array" => $posts_array]);
PHPStorm ругается на `Undefined variable`

Мне это не очень нравится. Какие варианты..?

* Забить и отключить инспекцию
* Добавить DocBlock и указать все переменные, например 
```php
/**
 * @var array $posts_array
 */
 ```

* Заменить переменные с данными на функции
* Свой вариант)

2022-03-26 17:46 UTC, EvgenyRomanov commented on index.php
> +$main = include_template("main.php", ["posts_array" => $posts_array]);
Добавил DocBlock. Конечно, по заданию не нужно было помещать данные в отдельный файл, но очень хотелось отделить их от кода, тем более что в лекционном материале к заданию именно так и сделано.

2022-03-26 17:47 UTC, EvgenyRomanov commented on templates/main.php
> +                        <?php elseif($post['type'] === 'post-text'):?>
Да =) тут, конечно, сглупил: перепутал местами две функции и не проверил отображение после изменений в коде.
Для верности добавил текст карточки js-код, как видно, htmlspecialchars() теперь отрабатывает как нужно и стили не ломаются.

2022-03-26 17:47 UTC, EvgenyRomanov commented on index.php
> +require_once 'data.php';
data.php вынес в отдельную директорию data

2022-03-26 17:48 UTC, EvgenyRomanov commented on templates/data.php
> +<?php
data.php вынес в отдельную директорию data

2022-03-30 08:06 UTC, esbobkov commented on index.php
> +$main = include_template("main.php", ["posts_array" => $posts_array]);
Как вариант, данные можно еще положить в файлики (json, csv) и оттуда их декодить.

2022-03-30 08:07 UTC, esbobkov approved these changes

2022-03-30 08:07 UTC, merged