module3-task2
htmlacademy-php/2039497-readme-12 pull request #8
Opened 2022-04-03 18:50 UTC by EvgenyRomanov

2022-04-06 09:26 UTC, esbobkov requested changes
Пример из задания не работает
> 2019-11-10 09:45 > 2 дня назад;
У тебя возвращается `1 день назад`

2022-04-06 09:26 UTC, esbobkov commented on helpers.php
> +function get_diff_date($date)
Тип аргумента и возвращаемого значения лучше указать в коде, а не в PHPDoc

2022-04-06 09:26 UTC, esbobkov commented on helpers.php
> +    $current_date = date_create("now");
Аргумент не нужен, т.к. по дефолту и так `now`

2022-04-06 09:26 UTC, esbobkov commented on helpers.php
> +    $all_days_count = intval(date_interval_format($diff, "%a"));
intval это что-то древнее, лучше просто кастинг использовать `(int)`

2022-04-06 09:26 UTC, esbobkov commented on helpers.php
> +        return $minutes_count . " " .
тут снова какой-то микс из кавычек и смотрится в целом сложно.
Возможно используя `sprintf` код будет выглядеть более понятно и лаконично

2022-04-06 09:26 UTC, esbobkov commented on helpers.php
> +    if (!($years_count || $months_count || $weeks_count || $days_count || $hours_count))
Отсутствуют фигурные скобки у блоков  `if`

2022-04-06 15:52 UTC, EvgenyRomanov commented on helpers.php
> +    if (!($years_count || $months_count || $weeks_count || $days_count || $hours_count))
Изменил содержимое функции, данное замечание учел.

2022-04-06 15:52 UTC, EvgenyRomanov commented on helpers.php
> +        return $minutes_count . " " .
Изменил содержимое функции, данное замечание учел.

2022-04-06 15:53 UTC, EvgenyRomanov commented on helpers.php
> +    $all_days_count = intval(date_interval_format($diff, "%a"));
Изменил содержимое функции, данное замечание учел.

2022-04-06 15:53 UTC, EvgenyRomanov commented on helpers.php
> +    $current_date = date_create("now");
Изменил содержимое функции, данное замечание учел.

2022-04-06 15:55 UTC, EvgenyRomanov commented on helpers.php
> +function get_diff_date($date)
Указал в коде возвращаемый тип. В PHPDoc написал, чтобы в целом соблюдать стиль написания функций в файле helpers.php

2022-04-06 16:03 UTC, EvgenyRomanov commented
> Пример из задания не работает
> 
> > 2019-11-10 09:45 > 2 дня назад;
> > У тебя возвращается `1 день назад`

Переработал функцию, данное замечание исправил.
А вообще данная ошибка возникла потому, что в задании нормально не указано (или просто я не понял), как нужно округлять время, есть противоречия. Например, указано, что округлять "в большую сторону", я это понимаю, что условно 14:05 это 15:00.
При этом в тексте задания предлагается использовать в решении функцию floor(), которая округляет вниз.
А в приведенных примерах округление работает уже "математически" (0,5 -> 1).

2022-04-09 07:30 UTC, esbobkov approved these changes

2022-04-09 07:30 UTC, esbobkov commented on helpers.php
> +function get_diff_date($date) : string
Можно добавить тип аргумента `function get_diff_date(DateTime $date) : string`

2022-04-09 07:30 UTC, merged

2022-04-14 12:06 UTC, esbobkov commented
> 

> Периоды округляются в большую сторону

соответственно 
Если сейчас: 2019-11-12 04:20
Дата поста: 2019-11-10 09:45

Получается, прошло 1 день 18 часов 35 минут 
при округлении до дней в большую сторону, получится 2 дня