Module4 task1
htmlacademy-php/2039497-readme-12 pull request #9
Opened 2022-04-23 21:28 UTC by EvgenyRomanov

2022-04-27 13:57 UTC, esbobkov requested changes

2022-04-27 13:57 UTC, esbobkov commented on schema.sql
> +USE `readme`;
USE вроде как здесь не нужен

2022-04-27 13:57 UTC, esbobkov commented on schema.sql
> +    `date_create` DATETIME NOT NULL,                      -- дата и время, когда этот пользователь завёл аккаунт
все хорошо, просто я привык, что подобные поля называются `created_at`, `updated_at` и т.д

2022-04-27 13:57 UTC, esbobkov commented on schema.sql
> +    `password` CHAR(64) NOT NULL,                         -- хэшированный пароль пользователя
почему именно `CHAR(64)`?

2022-04-27 13:57 UTC, esbobkov commented on schema.sql
> +    `type` VARCHAR(128) NOT NULL,                     -- название (Текст, Цитата, Картинка, Видео, Ссылка)
`type` - уникальный же?

2022-04-27 13:57 UTC, esbobkov commented on schema.sql
> +    `class_name` VARCHAR(128)                         -- имя класса для иконки (photo, video, text, quote, link)
кажется не очень хорошо, что детали верстки протекли в БД.
Я бы маппил в коде.

2022-04-27 13:57 UTC, esbobkov commented on schema.sql
> +    FULLTEXT `ft1` (`header`,`content_text`, `author_quote`)   -- ключ для полнотекстового поиска
прикольно :+1: 


вопрос у меня только к имени индекса, лучше тогда его более осмысленно назвать
инача, по мере роста проекта будут сплошные трехбуквенные непонятные сокращения)

2022-04-27 13:57 UTC, esbobkov commented on schema.sql
> +    `content_text` MEDIUMTEXT,                                 -- текстовое содержимое: задаётся пользователем
Думаешь `TEXT` может не хватить?)

2022-04-27 13:57 UTC, esbobkov commented on schema.sql
> +    INDEX `hti` (`hashtag`)
что такое `hti`?
зачем так сокращать? вообще имя индекса же автоматически генерируется?

2022-04-27 13:57 UTC, esbobkov commented on schema.sql
> +    `comment` TEXT,                                  -- содержимое: задается пользователем
nullable ?

2022-04-27 13:57 UTC, esbobkov commented on schema.sql
> +    FOREIGN KEY (`post_id`) REFERENCES `posts` (`id`)
по идее, везде где у нас `FOREIGN KEY` можно добавить `INDEX` сразу

2022-04-27 13:57 UTC, esbobkov commented on schema.sql
> +    `dst_post_id` INT NOT NULL,
о, нет, давай не будем вводить сокращения)

2022-04-27 13:57 UTC, esbobkov commented on schema.sql
> +    `role` VARCHAR(64) NOT NULL
роль уникальная поидее

2022-05-04 20:10 UTC, EvgenyRomanov commented on schema.sql
> +    `password` CHAR(64) NOT NULL,                         -- хэшированный пароль пользователя
Сhar выбрал потому, что выделяемая память будет постоянной - 64 байта, ни больше, ни меньше.
Пароли по заданию хранятся в хэшированном виде, а длинна хэша всегда постоянна.
Такая была логика. 
А 64 - тут, честно сказать, просто увидел в примере. Вероятно, зависит от выбора хэш-функции.

2022-05-04 20:12 UTC, EvgenyRomanov commented on schema.sql
> +    `type` VARCHAR(128) NOT NULL,                     -- название (Текст, Цитата, Картинка, Видео, Ссылка)
Согласен, исправил.

2022-05-04 20:15 UTC, EvgenyRomanov commented on schema.sql
> +    `class_name` VARCHAR(128)                         -- имя класса для иконки (photo, video, text, quote, link)
возможно, но тут я ссылался на задание, где описаны все сущности

<img width="388" alt="image" src="https://user-images.githubusercontent.com/43170380/166818494-7f9378dc-868f-4fdb-b0ad-287d7053ee1e.png">

2022-05-04 20:37 UTC, EvgenyRomanov commented on schema.sql
> +    `date_create` DATETIME NOT NULL,                      -- дата и время, когда этот пользователь завёл аккаунт
Учел.

2022-05-04 20:38 UTC, EvgenyRomanov commented on schema.sql
> +    INDEX `hti` (`hashtag`)
Исправил сокращение, не хватает боевой практики =) 
INDEX добавил, смотря на общее ТЗ, т.к. будет осуществляться поиск по тегам. Возможно, я не прав и тут не уместна такая конструкция.

2022-05-04 20:41 UTC, EvgenyRomanov commented on schema.sql
> +    `comment` TEXT,                                  -- содержимое: задается пользователем
Да, нелогично получилось..Исправил.

2022-05-04 21:00 UTC, EvgenyRomanov commented on schema.sql
> +    `role` VARCHAR(64) NOT NULL
Да, это ошибка. Исправил.

2022-05-04 21:00 UTC, EvgenyRomanov commented on schema.sql
> +    `dst_post_id` INT NOT NULL,
Беру во внимание)

2022-05-04 21:05 UTC, EvgenyRomanov commented on schema.sql
> +USE `readme`;
При выполнении скрипта sql ошибка вылетает, что не выбрана база. Поэтому оставил.

2022-05-04 21:29 UTC, EvgenyRomanov commented on schema.sql
> +    `content_text` MEDIUMTEXT,                                 -- текстовое содержимое: задаётся пользователем
Мало ли =) Были сомнения, но теперь ты их развеял

2022-05-06 07:14 UTC, esbobkov commented on schema.sql
> +    `class_name` VARCHAR(128)                         -- имя класса для иконки (photo, video, text, quote, link)
странное решение конечно, но раз в ТЗ так, то ок

2022-05-06 07:15 UTC, merged